### ISSUE TITLE
树莓派与传感器

### ISSUE THREAD

**Issue by sunchenguang** [wwj718/awesome-raspberry-pi-zh#1]
除了上述的资源，可以增加一些树莓派与传感器交互的资料，比如超声波测距，红外感应等。更丰富更实用。

**Comment by wwj718** [comment]
@sunchenguang 好主意，先搜罗一下这方面的资料

**Comment by ReidHolmes** [comment]
有一段时间玩过kali kinux，那段时间想买树莓派来着。可惜最终没买成。日后折腾的话会再来哥这里的。

**Comment by wwj718** [comment]
@ReidHolmes  我把kali装到树莓派里呢，简直可以复现《黑客军团》里的剧情
