### ISSUE TITLE
参与方式

### ISSUE THREAD

**Issue by spy19930412** [wwj718/awesome-raspberry-pi-zh#3]
在文章和教程看起来很不错的样子，如果有空，或许可以帮忙翻译（如果确实有必要的话），想问学长有必要么，如果有的话，如何提交呢～

**Comment by wwj718** [comment]
好的呀 我最近正好事情多 如果愿意翻译再好不过啦！提交的话 把这个项目fork一份 添加完翻译的新内容发个pr给我就好啦！

**Comment by liuhaoXD** [comment]
我已经提交PR了
